"""adding table and fields to track

Revision ID: 017a1fe21ec4
Revises: 47f67b74af58
Create Date: 2018-09-18 16:50:43.763412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017a1fe21ec4'
down_revision = '47f67b74af58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LJFT',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_LJFT_count'), 'LJFT', ['count'], unique=False)
    op.create_index(op.f('ix_LJFT_date'), 'LJFT', ['date'], unique=False)
    op.create_index(op.f('ix_LJFT_status'), 'LJFT', ['status'], unique=False)
    op.create_index(op.f('ix_LJFT_team'), 'LJFT', ['team'], unique=False)
    op.create_table('buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buckets_count'), 'buckets', ['count'], unique=False)
    op.create_index(op.f('ix_buckets_date'), 'buckets', ['date'], unique=False)
    op.create_index(op.f('ix_buckets_status'), 'buckets', ['status'], unique=False)
    op.create_index(op.f('ix_buckets_team'), 'buckets', ['team'], unique=False)
    op.add_column('leaver', sa.Column('outprosshell', sa.DateTime(), nullable=True))
    op.add_column('leaver', sa.Column('trackend', sa.DateTime(), nullable=True))
    op.add_column('leaver', sa.Column('trackstart', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_leaver_outprosshell'), 'leaver', ['outprosshell'], unique=False)
    op.create_index(op.f('ix_leaver_trackend'), 'leaver', ['trackend'], unique=False)
    op.create_index(op.f('ix_leaver_trackstart'), 'leaver', ['trackstart'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaver_trackstart'), table_name='leaver')
    op.drop_index(op.f('ix_leaver_trackend'), table_name='leaver')
    op.drop_index(op.f('ix_leaver_outprosshell'), table_name='leaver')
    op.drop_column('leaver', 'trackstart')
    op.drop_column('leaver', 'trackend')
    op.drop_column('leaver', 'outprosshell')
    op.drop_index(op.f('ix_buckets_team'), table_name='buckets')
    op.drop_index(op.f('ix_buckets_status'), table_name='buckets')
    op.drop_index(op.f('ix_buckets_date'), table_name='buckets')
    op.drop_index(op.f('ix_buckets_count'), table_name='buckets')
    op.drop_table('buckets')
    op.drop_index(op.f('ix_LJFT_team'), table_name='LJFT')
    op.drop_index(op.f('ix_LJFT_status'), table_name='LJFT')
    op.drop_index(op.f('ix_LJFT_date'), table_name='LJFT')
    op.drop_index(op.f('ix_LJFT_count'), table_name='LJFT')
    op.drop_table('LJFT')
    # ### end Alembic commands ###
