"""empty message

Revision ID: 47f67b74af58
Revises: 3f0a3a69bf4b
Create Date: 2018-08-24 22:08:05.451989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f67b74af58'
down_revision = '3f0a3a69bf4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaver', sa.Column('suspectcheck', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_leaver_suspectcheck'), 'leaver', ['suspectcheck'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaver_suspectcheck'), table_name='leaver')
    op.drop_column('leaver', 'suspectcheck')
    # ### end Alembic commands ###
