"""empty message

Revision ID: 7aef9c20f954
Revises: bac49c3b7209
Create Date: 2018-08-22 19:20:55.596853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aef9c20f954'
down_revision = 'bac49c3b7209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaver', sa.Column('datetimeresult', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_leaver_datetimeresult'), 'leaver', ['datetimeresult'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaver_datetimeresult'), table_name='leaver')
    op.drop_column('leaver', 'datetimeresult')
    # ### end Alembic commands ###
