"""+ engagement times

Revision ID: c95a91dfc64b
Revises: 017a1fe21ec4
Create Date: 2018-10-05 17:07:45.046363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95a91dfc64b'
down_revision = '017a1fe21ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaver', sa.Column('eend', sa.DateTime(), nullable=True))
    op.add_column('leaver', sa.Column('estart', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_leaver_eend'), 'leaver', ['eend'], unique=False)
    op.create_index(op.f('ix_leaver_estart'), 'leaver', ['estart'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaver_estart'), table_name='leaver')
    op.drop_index(op.f('ix_leaver_eend'), table_name='leaver')
    op.drop_column('leaver', 'estart')
    op.drop_column('leaver', 'eend')
    # ### end Alembic commands ###
